import type { Department, Employee, Project } from "./types";

export const seedDepartments: Department[] = [
  { id: "d1", name: "Engineering", description: "Platform, product and infrastructure teams" },
  { id: "d2", name: "Design", description: "Product design, brand and research" },
  { id: "d3", name: "Sales", description: "Enterprise and mid-market revenue" },
  { id: "d4", name: "People Ops", description: "Hiring, culture and employee experience" },
  { id: "d5", name: "Finance", description: "Accounting, payroll and planning" },
];

export const seedEmployees: Employee[] = [
  {
    id: "e1",
    name: "Aarav Mehta",
    email: "aarav.mehta@atlas.co",
    designation: "Senior Backend Engineer",
    departmentId: "d1",
    salary: 1850000,
    dateOfJoining: "2021-03-15",
  },
  {
    id: "e2",
    name: "Sofia Alvarez",
    email: "sofia.alvarez@atlas.co",
    designation: "Product Designer",
    departmentId: "d2",
    salary: 1420000,
    dateOfJoining: "2022-07-04",
  },
  {
    id: "e3",
    name: "Liam O'Connor",
    email: "liam.oconnor@atlas.co",
    designation: "Account Executive",
    departmentId: "d3",
    salary: 1180000,
    dateOfJoining: "2023-01-09",
  },
  {
    id: "e4",
    name: "Priya Raghavan",
    email: "priya.raghavan@atlas.co",
    designation: "Engineering Manager",
    departmentId: "d1",
    salary: 2400000,
    dateOfJoining: "2019-11-25",
  },
  {
    id: "e5",
    name: "Noah Fischer",
    email: "noah.fischer@atlas.co",
    designation: "People Partner",
    departmentId: "d4",
    salary: 980000,
    dateOfJoining: "2023-06-12",
  },
  {
    id: "e6",
    name: "Emma Laurent",
    email: "emma.laurent@atlas.co",
    designation: "Financial Analyst",
    departmentId: "d5",
    salary: 1050000,
    dateOfJoining: "2022-02-28",
  },
  {
    id: "e7",
    name: "Kenji Nakamura",
    email: "kenji.nakamura@atlas.co",
    designation: "Frontend Engineer",
    departmentId: "d1",
    salary: 1590000,
    dateOfJoining: "2024-04-02",
  },
  {
    id: "e8",
    name: "Zara Okafor",
    email: "zara.okafor@atlas.co",
    designation: "Brand Designer",
    departmentId: "d2",
    salary: 1120000,
    dateOfJoining: "2024-09-16",
  },
  {
    id: "e9",
    name: "Marcus Bright",
    email: "marcus.bright@atlas.co",
    designation: "Sales Development Rep",
    departmentId: "d3",
    salary: 760000,
    dateOfJoining: "2025-02-03",
  },
  {
    id: "e10",
    name: "Ines Duarte",
    email: "ines.duarte@atlas.co",
    designation: "Site Reliability Engineer",
    departmentId: "d1",
    salary: 1720000,
    dateOfJoining: "2020-08-19",
  },
  {
    id: "e11",
    name: "Tomás Silva",
    email: "tomas.silva@atlas.co",
    designation: "Recruiter",
    departmentId: "d4",
    salary: 890000,
    dateOfJoining: "2025-05-21",
  },
  {
    id: "e12",
    name: "Hannah Weiss",
    email: "hannah.weiss@atlas.co",
    designation: "Payroll Specialist",
    departmentId: "d5",
    salary: 810000,
    dateOfJoining: "2026-01-12",
  },
];

export const seedProjects: Project[] = [
  {
    id: "p1",
    name: "Atlas Core Migration",
    location: "Bengaluru",
    startDate: "2025-01-15",
    employeeId: "e1",
  },
  { id: "p2", name: "Design System 3.0", location: "Lisbon", startDate: "2025-03-02", employeeId: "e2" },
  { id: "p3", name: "Enterprise Pipeline", location: "Dublin", startDate: "2025-04-18", employeeId: "e3" },
  { id: "p4", name: "Observability Revamp", location: "Bengaluru", startDate: "2024-10-07", employeeId: "e10" },
  { id: "p5", name: "Hiring Funnel Rebuild", location: "Berlin", startDate: "2025-08-11", employeeId: "e5" },
  { id: "p6", name: "Payroll Automation", location: "Paris", startDate: "2026-02-01", employeeId: "e6" },
  { id: "p7", name: "Mobile App Refresh", location: "Tokyo", startDate: "2025-11-20", employeeId: "e7" },
  { id: "p8", name: "Brand Refresh", location: "Lagos", startDate: "2026-03-09", employeeId: "e8" },
  { id: "p9", name: "Platform Scaling", location: "Bengaluru", startDate: "2026-05-04", employeeId: "e1" },
];
